scoreboard:
  title: "&#08fb6aS&#0ef279i&#14e989l&#1ae098v&#20d7a8e&#25cdb7r&#2bc4c7R&#31bbd6u&#37b2e6s&#3da9f5h"
  header:
    - "&7%server_time_yyyy-MM-dd% {serial}"
  footer:
      - "&bMh&axj&f.&eCl&6ub"
  waiting:
    - ""
    - "{players}"
    - ""
    - "{countdown}"
    - ""
    - "&f版本: &b1.0"
    - ""
  playing:
    - ""
    - "{double}" #蠹虫翻倍提示
    - ""
    - "[urs]"
    - ""
    - "&f蠹虫数量排行"
    - "{rank_1}" #
    - "{rank_2}"
    - "{rank_3}"
    - " "
  ending:
    - ""
    - "&c游戏结束！"
    - ""
start-notice:
  - "===================================="
  - "&6&l游戏开始！"
  - ""
  - "&7&l蠹虫追杀！"
  - "&f你需要在蠹虫的追杀下活着！"
  - "&f蠹虫将在死亡后分裂成两只新蠹虫！"
  - "&f每60秒蠹虫数量翻倍！"
  - "&f笑到最后的才是赢家！"
  - ""
  - "===================================="
end-notice:
    - "===================================="
    - "&6&l游戏结束！"
    - ""
    - "&f恭喜: &6{winner} &f活到了最后！！"
    - ""
    - "最终排行榜 (名字 - 蠹虫数量)"
    - "&e#&41 &f{name1} &7- &e{qty1}"
    - "&e#&c2 &f{name2} &7- &e{qty2}"
    - "&e#&63 &f{name3} &7- &e{qty3}"
    - ""
    - "===================================="